# Generated by Django 5.1.1 on 2025-06-21 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drillquestion',
            name='sign_language_instructions',
        ),
        migrations.RemoveField(
            model_name='drillquestion',
            name='story_context',
        ),
        migrations.RemoveField(
            model_name='drillquestion',
            name='story_title',
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 21, 9, 50, 58, 719067, tzinfo=datetime.timezone.utc)),
        ),
    ]
