# Generated by Django 5.2 on 2025-04-18 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name_encrypted',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_encrypted',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 18, 17, 17, 36, 61446, tzinfo=datetime.timezone.utc)),
        ),
    ]
