# Generated by Django 5.1.1 on 2025-09-24 17:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_drillquestion_sign_language_instructions_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorygameresult',
            name='question',
        ),
        migrations.RemoveField(
            model_name='drillchoice',
            name='question',
        ),
        
        migrations.AddField(
            model_name='questionresult',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='questionresult',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='questionresult',
            unique_together={('drill_result', 'content_type', 'object_id')},
        ),
        migrations.AddField(
            model_name='drillchoice',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='drillchoice',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memorygameresult',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='memorygameresult',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drill',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 24, 18, 38, 24, 833063, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='BlankBustersQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'Smart Select'), ('B', 'Blank Busters'), ('D', 'Sentence Builder'), ('P', 'Picture Word'), ('G', 'Memory Game')], default='S', max_length=1)),
                ('text', models.CharField(max_length=200)),
                ('word', models.CharField(blank=True, max_length=255, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('letterChoices', models.JSONField(blank=True, null=True)),
                ('answer', models.CharField(blank=True, max_length=200, null=True)),
                ('pattern', models.CharField(blank=True, max_length=200, null=True)),
                ('hint', models.TextField(blank=True, null=True)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_questions', to='api.drill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemoryGameQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'Smart Select'), ('B', 'Blank Busters'), ('D', 'Sentence Builder'), ('P', 'Picture Word'), ('G', 'Memory Game')], default='S', max_length=1)),
                ('text', models.CharField(max_length=200)),
                ('word', models.CharField(blank=True, max_length=255, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('memoryCards', models.JSONField(blank=True, default=list, null=True)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_questions', to='api.drill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PictureWordQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'Smart Select'), ('B', 'Blank Busters'), ('D', 'Sentence Builder'), ('P', 'Picture Word'), ('G', 'Memory Game')], default='S', max_length=1)),
                ('text', models.CharField(max_length=200)),
                ('word', models.CharField(blank=True, max_length=255, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('pictureWord', models.JSONField(blank=True, default=list, null=True)),
                ('answer_text', models.CharField(blank=True, max_length=200, null=True)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_questions', to='api.drill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SentenceBuilderQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'Smart Select'), ('B', 'Blank Busters'), ('D', 'Sentence Builder'), ('P', 'Picture Word'), ('G', 'Memory Game')], default='S', max_length=1)),
                ('text', models.CharField(max_length=200)),
                ('word', models.CharField(blank=True, max_length=255, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('sentence', models.TextField(blank=True, null=True)),
                ('dragItems', models.JSONField(blank=True, default=list, null=True)),
                ('incorrectChoices', models.JSONField(blank=True, default=list, null=True)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_questions', to='api.drill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmartSelectQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'Smart Select'), ('B', 'Blank Busters'), ('D', 'Sentence Builder'), ('P', 'Picture Word'), ('G', 'Memory Game')], default='S', max_length=1)),
                ('text', models.CharField(max_length=200)),
                ('word', models.CharField(blank=True, max_length=255, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('answer_index', models.IntegerField(blank=True, null=True)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_questions', to='api.drill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='questionresult',
            name='question',
        ),
        migrations.DeleteModel(
            name='DrillQuestion',
        ),
    ]
