# Generated by Django 5.1.1 on 2025-04-15 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 15, 16, 19, 21, 294716, tzinfo=datetime.timezone.utc)),
        ),
    ]
