# Generated by Django 5.1.1 on 2025-09-25 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_memorygameresult_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picturewordquestion',
            old_name='answer_text',
            new_name='answer',
        ),
        migrations.AlterField(
            model_name='blankbustersquestion',
            name='type',
            field=models.CharField(choices=[('M', 'Smart Select'), ('F', 'Blank Busters'), ('D', 'Sentence Builder'), ('P', 'Picture Word'), ('G', 'Memory Game')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='memorygamequestion',
            name='type',
            field=models.CharField(choices=[('M', 'Smart Select'), ('F', 'Blank Busters'), ('D', 'Sentence Builder'), ('P', 'Picture Word'), ('G', 'Memory Game')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 25, 11, 8, 4, 944389, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='picturewordquestion',
            name='type',
            field=models.CharField(choices=[('M', 'Smart Select'), ('F', 'Blank Busters'), ('D', 'Sentence Builder'), ('P', 'Picture Word'), ('G', 'Memory Game')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='sentencebuilderquestion',
            name='type',
            field=models.CharField(choices=[('M', 'Smart Select'), ('F', 'Blank Busters'), ('D', 'Sentence Builder'), ('P', 'Picture Word'), ('G', 'Memory Game')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='smartselectquestion',
            name='type',
            field=models.CharField(choices=[('M', 'Smart Select'), ('F', 'Blank Busters'), ('D', 'Sentence Builder'), ('P', 'Picture Word'), ('G', 'Memory Game')], default='S', max_length=1),
        ),
    ]
