# Generated by Django 5.1.1 on 2025-09-25 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_answer_text_picturewordquestion_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartselectquestion',
            name='answer_index',
        ),
        migrations.AddField(
            model_name='smartselectquestion',
            name='answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 25, 11, 52, 33, 216560, tzinfo=datetime.timezone.utc)),
        ),
    ]
