# Generated by Django 5.1.1 on 2025-09-30 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_smartselectquestion_answer_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 30, 12, 7, 51, 355485, tzinfo=datetime.timezone.utc)),
        ),
    ]
