# Generated by Django 5.2 on 2025-04-22 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_classroom_class_code_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 11, 9, 51, 682535, tzinfo=datetime.timezone.utc)),
        ),
    ]
