# Generated by Django 5.1.1 on 2025-10-01 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='wordlist_name',
            field=models.CharField(blank=True, help_text='Name of built-in wordlist used for this drill', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 1, 9, 51, 55, 349447, tzinfo=datetime.timezone.utc)),
        ),
    ]
