# Generated by Django 5.2 on 2025-04-22 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='color',
            field=models.CharField(default='#7D83D7', max_length=7),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 11, 42, 51, 409985, tzinfo=datetime.timezone.utc)),
        ),
    ]
