# Generated by Django 5.1.1 on 2025-10-01 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_drill_wordlist_name_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 1, 10, 4, 12, 425012, tzinfo=datetime.timezone.utc)),
        ),
    ]
