# Generated by Django 5.2 on 2025-04-22 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_classroom_color_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 11, 43, 25, 218785, tzinfo=datetime.timezone.utc)),
        ),
    ]
