# Generated by Django 5.1.1 on 2025-10-03 09:05

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drill',
            name='wordlist_name',
        ),
        migrations.AddField(
            model_name='drill',
            name='open_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 3, 9, 43, 31, 454927, tzinfo=datetime.timezone.utc)),
        ),
    ]
