# Generated by Django 5.1.1 on 2025-10-03 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_drill_wordlist_name_drill_open_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 3, 10, 7, 0, 715925, tzinfo=datetime.timezone.utc)),
        ),
    ]
