# Generated by Django 5.1.1 on 2025-10-03 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 3, 10, 29, 22, 777354, tzinfo=datetime.timezone.utc)),
        ),
    ]
