# Generated by Django 5.2 on 2025-04-22 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_avatar_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classroom',
            name='student_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 21, 58, 9, 309504, tzinfo=datetime.timezone.utc)),
        ),
    ]
