# Generated by Django 5.1.1 on 2025-10-03 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='wordlist_name',
            field=models.CharField(blank=True, help_text='Name of built-in wordlist used for this drill', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 3, 16, 20, 39, 173701, tzinfo=datetime.timezone.utc)),
        ),
    ]
