# Generated by Django 5.2 on 2025-04-22 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_classroom_is_hidden_classroom_student_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='classroom',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 23, 14, 46, 709998, tzinfo=datetime.timezone.utc)),
        ),
    ]
