# Generated by Django 5.2 on 2025-05-07 14:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_classroom_options_classroom_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 7, 15, 56, 11, 501555, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('total_run', models.PositiveIntegerField(default=1)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drills', to='api.classroom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DrillQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=200)),
                ('type', models.CharField(choices=[('M', 'Multiple Choice'), ('D', 'Drag and Drop'), ('F', 'Fill in the Blank')], default='M', max_length=1)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.drill')),
            ],
        ),
        migrations.CreateModel(
            name='DrillChoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='drill_choices/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='drill_choices/videos/')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='api.drillquestion')),
            ],
        ),
        migrations.CreateModel(
            name='DrillResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run_number', models.IntegerField(verbose_name=4)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('completion_time', models.DateTimeField()),
                ('points', models.FloatField()),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drill_results', to='api.drill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drill_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('definition', models.CharField(max_length=200)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='api.wordlist')),
            ],
        ),
    ]
