# Generated by Django 5.1.7 on 2025-10-04 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_drill_wordlist_name_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='is_first_drill',
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 4, 18, 59, 42, 263146, tzinfo=datetime.timezone.utc)),
        ),
    ]
