# Generated by Django 5.2 on 2025-05-08 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_wordlist_alter_passwordreset_expires_at_drill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 23, 9, 52, 445202, tzinfo=datetime.timezone.utc)),
        ),
    ]
