# Generated by Django 5.2 on 2025-05-10 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_drill_status_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillquestion',
            name='blankPosition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drillquestion',
            name='dragItems',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='drillquestion',
            name='dropZones',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 10, 5, 13, 40, 903709, tzinfo=datetime.timezone.utc)),
        ),
    ]
