# Generated by Django 5.2 on 2025-05-11 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_drillquestion_blankposition_drillquestion_dragitems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='title',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 0, 15, 30, 239000, tzinfo=datetime.timezone.utc)),
        ),
    ]
