# Generated by Django 5.2 on 2025-05-16 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_drill_title_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 18, 57, 4, 344722, tzinfo=datetime.timezone.utc)),
        ),
    ]
