# Generated by Django 5.1.1 on 2025-05-16 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_drillquestion_memorycards_alter_drillquestion_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 16, 30, 41, 771633, tzinfo=datetime.timezone.utc)),
        ),
    ]
