# Generated by Django 5.1.1 on 2025-05-20 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_classroom_is_archived_alter_passwordreset_expires_at'),
        ('api', '0018_alter_passwordreset_expires_at'),
    ]

    operations = [
    ]
