# Generated by Django 5.2 on 2025-05-20 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_create_transfer_request_and_notification'),
        ('api', '0019_merge_20250520_1902'),
    ]

    operations = [
    ]
