# Generated by Django 5.1.1 on 2025-05-20 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_merge_20250521_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillquestion',
            name='sign_language_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drillquestion',
            name='story_context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drillquestion',
            name='story_image',
            field=models.ImageField(blank=True, null=True, upload_to='drill_stories/images/'),
        ),
        migrations.AddField(
            model_name='drillquestion',
            name='story_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drillquestion',
            name='story_video',
            field=models.FileField(blank=True, null=True, upload_to='drill_stories/videos/'),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 20, 19, 6, 14, 74155, tzinfo=datetime.timezone.utc)),
        ),
    ]
