# Generated by Django 5.2 on 2025-05-20 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_merge_20250520_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='color',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='order',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='student_color',
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 20, 14, 26, 22, 133180, tzinfo=datetime.timezone.utc)),
        ),
    ]
