# Generated by Django 5.1.1 on 2025-05-21 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_drillquestion_sign_language_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 15, 33, 13, 94044, tzinfo=datetime.timezone.utc)),
        ),
    ]
