# Generated by Django 5.1.1 on 2025-05-21 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drillquestion',
            name='story_image',
        ),
        migrations.RemoveField(
            model_name='drillquestion',
            name='story_video',
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 15, 33, 30, 138894, tzinfo=datetime.timezone.utc)),
        ),
    ]
