# Generated by Django 5.1.1 on 2025-05-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_classroom_options_remove_classroom_color_and_more'),
        ('api', '0020_merge_20250520_1912'),
        ('api', '0022_remove_drillquestion_story_image_and_more'),
    ]

    operations = [
    ]
