# Generated by Django 5.1.7 on 2025-05-22 11:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_merge_20250521_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='image_url',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='video_url',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='wordlist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_word_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 22, 12, 0, 38, 639382, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
