# Generated by Django 5.2 on 2025-05-21 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_merge_20250521_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 17, 6, 56, 39433, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
