# Generated by Django 5.2 on 2025-05-21 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_notification_id_alter_passwordreset_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 17, 8, 2, 236727, tzinfo=datetime.timezone.utc)),
        ),
    ]
