# Generated by Django 5.1.1 on 2025-05-22 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_vocabulary_image_url_vocabulary_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillquestion',
            name='pictureWord',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='drillquestion',
            name='type',
            field=models.CharField(choices=[('M', 'Multiple Choice'), ('D', 'Drag and Drop'), ('F', 'Fill in the Blank'), ('G', 'Memory Game'), ('P', 'Picture Word')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 22, 15, 50, 5, 126008, tzinfo=datetime.timezone.utc)),
        ),
    ]
