# Generated by Django 5.1.1 on 2025-05-23 19:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_drillquestion_answer_drillquestion_pictureword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 23, 20, 8, 39, 886213, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='QuestionResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submitted_answer', models.JSONField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken', models.FloatField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('drill_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_results', to='api.drillresult')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_results', to='api.drillquestion')),
            ],
            options={
                'unique_together': {('drill_result', 'question')},
            },
        ),
    ]
