# Generated by Django 5.1.1 on 2025-05-22 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_drillquestion_pictureword_alter_drillquestion_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillquestion',
            name='answer',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 22, 19, 35, 49, 880848, tzinfo=datetime.timezone.utc)),
        ),
    ]
