# Generated by Django 5.2 on 2025-05-24 17:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_drillquestion_answer_drillquestion_pictureword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='custom_wordlist',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drills', to='api.wordlist'),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 18, 30, 8, 190909, tzinfo=datetime.timezone.utc)),
        ),
    ]
