# Generated by Django 5.2 on 2025-05-26 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_drill_custom_wordlist_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillquestion',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drillquestion',
            name='incorrectChoices',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='drillquestion',
            name='pattern',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='drillquestion',
            name='sentence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 26, 9, 1, 27, 436642, tzinfo=datetime.timezone.utc)),
        ),
    ]
