# Generated by Django 5.1.1 on 2025-05-24 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_passwordreset_expires_at_questionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresult',
            name='points_awarded',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 18, 16, 28, 111349, tzinfo=datetime.timezone.utc)),
        ),
    ]
