# Generated by Django 5.2 on 2025-05-26 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_drillquestion_hint_drillquestion_incorrectchoices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillquestion',
            name='letterChoices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 26, 17, 56, 23, 70091, tzinfo=datetime.timezone.utc)),
        ),
    ]
