# Generated by Django 5.2 on 2025-05-25 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_passwordreset_expires_at'),
        ('api', '0027_questionresult_points_awarded_and_more'),
        ('api', '0028_add_badges'),
    ]

    operations = [
    ]
