# Generated by Django 5.2 on 2025-05-25 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_recreate_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('student_transfer', 'Student Transfer Request'), ('transfer_approved', 'Transfer Approved'), ('transfer_rejected', 'Transfer Rejected'), ('student_added', 'Student Added to Classroom'), ('student_removed', 'Student Removed from Classroom'), ('badge_earned', 'Badge Earned')], max_length=20),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 25, 20, 12, 46, 376493, tzinfo=datetime.timezone.utc)),
        ),
    ]
