# Generated by Django 5.2 on 2025-05-25 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 25, 20, 15, 28, 69836, tzinfo=datetime.timezone.utc)),
        ),
    ]
