# Generated by Django 5.2 on 2025-05-25 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 25, 20, 36, 29, 214205, tzinfo=datetime.timezone.utc)),
        ),
    ]
