# Generated by Django 5.1.1 on 2025-05-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_ensure_badges'),
        ('api', '0034_alter_passwordreset_expires_at'),
    ]

    operations = [
    ]
