# Generated by Django 5.1.1 on 2025-05-26 16:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_merge_20250526_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='custom_wordlist',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drills', to='api.wordlist'),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 26, 17, 30, 34, 230392, tzinfo=datetime.timezone.utc)),
        ),
    ]
