# Generated by Django 5.1.7 on 2025-05-27 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_badge_image_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 4, 6, 46, 428789, tzinfo=datetime.timezone.utc)),
        ),
    ]
