# Generated by Django 5.1.1 on 2025-05-27 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 19, 46, 21, 729045, tzinfo=datetime.timezone.utc)),
        ),
    ]
