# Generated by Django 5.1.1 on 2025-05-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_fix_pathfinder_badge'),
        ('api', '0042_alter_passwordreset_expires_at'),
    ]

    operations = [
    ]
