# Generated by Django 5.1.1 on 2025-05-27 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_award_pathfinder_badge'),
        ('api', '0043_merge_20250528_0249'),
    ]

    operations = [
    ]
