# Generated by Django 5.1.1 on 2025-05-27 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_award_pathfinder_badge_new'),
        ('api', '0044_merge_20250528_0255'),
    ]

    operations = [
    ]
