# Generated by Django 5.1.1 on 2025-05-27 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_merge_20250528_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 20, 16, 26, 858486, tzinfo=datetime.timezone.utc)),
        ),
    ]
