# Generated by Django 5.1.1 on 2025-05-27 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_update_pathfinder_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 21, 3, 57, 340199, tzinfo=datetime.timezone.utc)),
        ),
    ]
