# Generated by Django 5.1.7 on 2025-05-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_drillquestion_letterchoices_and_more'),
        ('api', '0048_alter_passwordreset_expires_at'),
    ]

    operations = [
    ]
