# Generated by Django 5.1.7 on 2025-05-29 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_drillresult__points_encrypted_temp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drillresult',
            old_name='_points_encrypted_temp',
            new_name='_points_encrypted',
        ),
        migrations.RemoveField(
            model_name='drillresult',
            name='points',
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 29, 12, 45, 36, 845737, tzinfo=datetime.timezone.utc)),
        ),
    ]
