# Generated by Django 5.1.7 on 2025-05-29 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_rename__points_encrypted_temp_drillresult__points_encrypted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 29, 13, 10, 5, 738042, tzinfo=datetime.timezone.utc)),
        ),
    ]
