# Generated by Django 5.1.7 on 2025-05-30 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillquestion',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drillquestion',
            name='word',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 30, 2, 42, 6, 429421, tzinfo=datetime.timezone.utc)),
        ),
    ]
